apiVersion: v1
kind: Pod
metadata:
  name: my-containerport-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myappcontainer
    image: nginx
    ports:
    - containerPort: 80
  restartPolicy: Never
