apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', "echo $(USER) $(PASSWORD) Hello, Kubernetes! && sleep 3600"]
    env:
    - name: USER
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: user
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
