apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    volumeMounts:
    - name: my-volume
      mountPath: /var/lib/mysql
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: mysql-pv-claim
