apiVersion: v1
kind: Service
metadata:
  name: pizza-service
  namespace: pizza
spec:
  type: NodePort
  selector:
    app: pizza-app
  ports:
    - protocol: TCP
      port: 30080
      targetPort: 80
